services:
  api:
    build: ./backend-test/backend
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    command: bash -c "python3 vectorsearch/manage.py runserver 0.0.0.0:8000"

  web:
    build: ./frontend-tests/my-react-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend